name: Maven Build and Publish

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  build:
    runs-on: self-hosted  # Run on your connected Linux instance

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the code from GitHub

      - name: Set Up JDK 17  # Change to your required JDK version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Temurin JDK
          java-version: '17'  # Change based on your project

      - name: Verify Java Installation
        run: java -version  # Check installed Java version

      - name: Build with Maven
        run: mvn clean install  # Runs the Maven build

      - name: Run Tests
        run: mvn test  # Run unit tests

      - name: Publish Artifact (if needed)
        run: mvn deploy  # Push to a Maven repository (Nexus, Artifactory, etc.)

      - name: Cleanup
        run: rm -rf target  # Cleanup after build
