name: Java Maven Build and Install Apache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Maven and install Apache
    runs-on: self-hosted  # Your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Build with Maven
        run: mvn clean install

      - name: Install Apache HTTP Server
        run: |
          sudo apt update
          sudo apt install -y apache2
          sudo systemctl enable apache2
          sudo systemctl start apache2
          sudo systemctl status apache2

      - name: Check Apache Version
        run: apache2 -v
